[workspace]
members = [
    "packages/*", 
    "contracts/bluna-vault",
    "contracts/whitelisted_contracts/mars_helper",
    "contracts/whitelisted_contracts/mars_fields_helper",
    "contracts/whitelisted_contracts/mirror_helper"
    # "contracts/*"
    ]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
