[workspace]
members = [
    "packages/white_whale", 
    "contracts/stablecoin-vault/profit-check",
    "contracts/stablecoin-vault/vault",
    "contracts/stablecoin-vault/peg-arb",
    "contracts/side-contracts/vesting",
    "contracts/side-contracts/lp_staking",
    "contracts/side-contracts/lp_staking_proxy",
    "contracts/treasury/treasury",
    "contracts/treasury/dapps/terraswap-dapp",
]

[net]
git-fetch-with-cli = true

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
