[workspace]
members = [
    "packages/ww-package", 
    "contracts/stablecoin-vault/profit-check",
    "contracts/stablecoin-vault/vault",
    "contracts/stablecoin-vault/peg-arb",
    "contracts/side-contracts/gov",
    "contracts/side-contracts/vesting",
    "contracts/side-contracts/community-fund",
    "contracts/luna-vault",

]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
