[package]
name = "whale-lp-emissions"
version = "1.0.0"
authors = ["Astromartian"]
edition = "2018"
license = "MIT"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
white-whale = { version = "1.0.0", path = "../../../packages/white_whale" }

cosmwasm-std = { version = "0.16.0", features = ["iterator"] }
cw20 = { version = "0.8.0" } 
cw20-base = { version = "0.8", features = ["library"] }
cw-storage-plus = "0.8"

cosmwasm-bignumber = "2.2.0"

schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "0.16.0"
cosmwasm-storage = { version = "0.16.0", features = ["iterator"] }
cw-multi-test =  { version = "0.8.0" } 