[package]
name = "signed_integer"
version = "0.1.0"
authors = ["MSNTCS <najafi@codechain.io>"]
edition = "2018"

[dependencies]
cosmwasm-std = { version = "0.16.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
