[package]
name = "dapp-template"
version = "0.1.0"
authors = ["CyberHoward", "Kerber0x", "0xFable"]
edition = "2018"
license = "MIT"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.16.7" }
cosmwasm-storage = { version = "0.16.7" }
cw-storage-plus = { version = "0.10" }
cw2 = { version = "0.10" }
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
white-whale = { version = "1.0.0", path = "../../../../packages/white_whale" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.7" }
cw-multi-test = { version = "0.8"}
terra-mocks = {git ="https://github.com/terra-money/cosmwasm-contracts.git", rev = "b25f4ac2d7bddaa3a18838cfe51d18e1ae855dcd", package = "terra-mocks"}
terra-multi-test = {git="https://github.com/astroport-fi/terra-plus", rev="b3991b9b109accf445fec086ce9792b197be6ca4", package = "terra-multi-test"}
terraswap = "2.4.0"
cw20-base = { version = "0.8", features = ["library"] }
cw20 = { version = "0.8" }
treasury = { version = "0.1.0", path = "../../treasury" }
memory = { version = "0.1.0", path = "../../memory" }
terraswap-factory = { version = "0.0.0", path = "../../../mocks/mock_terraswap/terraswap_factory" }
terraswap-pair = { version = "0.0.0", path = "../../../mocks/mock_terraswap/terraswap_pair" }
terraswap-token = { version = "0.0.0", path = "../../../mocks/mock_terraswap/terraswap_token" }
