[package]
name = "anchor"
version = "0.1.0"
authors = ["CyberHoward", "Kerber0x", "0xFable"]
edition = "2018"
license = "MIT"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.16.7" }
cw20 = { version = "0.8" }
cosmwasm-bignumber = "2.2"
terra-cosmwasm = "2.2"
terraswap = "2.4.0"
cosmwasm-storage = { version = "0.16.7" }
cw-storage-plus = { version = "0.10" }
cw-controllers = { version = "0.8" }
cw2 = { version = "0.10" }
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
white-whale = { version = "1.0.0", path = "../../../../packages/white_whale" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.7" }
