[package]
name = "white-whale"
version = "1.0.0"
authors = ["White Whale"]
edition = "2018"
description = "Common helpers for other white whale"
license = "Apache-2.0"
repository = "https://github.com/White-Whale-DeFi-Platform/contracts"
homepage = "https://whitewhale.finance"
documentation = "https://whitewhale.finance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
terra-cosmwasm = { version = "2.2.0" }
cosmwasm-bignumber = "2.2"
cosmwasm-std = { version = "0.16", features = ["iterator"] }
cosmwasm-storage = { version = "0.16", features = ["iterator"] }
cw-controllers = { version = "0.8" }
cw-storage-plus = { version = "0.8" }
cw20 = { version = "0.8" }
cw20-base = { version = "0.8", features = ["library"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
terraswap = "2.4.0"
thiserror = { version = "1.0.26" }
cw-multi-test = { version = "0.8"}
lazy_static = "1.4.0"
terra-mocks = {git ="https://github.com/terra-money/cosmwasm-contracts.git", rev = "b25f4ac2d7bddaa3a18838cfe51d18e1ae855dcd", package = "terra-mocks"}
terra-multi-test = {git="https://github.com/astroport-fi/terra-plus", rev="b3991b9b109accf445fec086ce9792b197be6ca4", package = "terra-multi-test"}
[dev-dependencies]
# cw-multi-test = { version = "0.8"}
stablecoin-vault = {version = "0.1.0", path = "../../contracts/stablecoin-vault"}
cw20-base = { version = "0.8", features = ["library"] } 
terra-multi-test = {git="https://github.com/astroport-fi/terra-plus", rev="b3991b9b109accf445fec086ce9792b197be6ca4", package = "terra-multi-test"}
