
name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          rustup default stable
          rustup target add wasm32-unknown-unknown
          rustup component add rust-analysis --toolchain stable-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu
          rustup component add rls --toolchain stable-x86_64-unknown-linux-gnu
          cargo install cargo-generate --features vendored-openssl

      - name: Run tests for stablecoin-vault
        working-directory: $GITHUB_WORKSPACE/stablecoin-vault
        run: |
          cargo update
          cargo unit-test
