name: Luna Vault

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - luna-vault-feature-branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: contracts/luna-vault

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.58.1
          target: wasm32-unknown-unknown
          override: true
          components: clippy, rustfmt
      - name: Run clippy
        run: cargo clippy --locked -- -D warnings
      - name: Run rustfmt
        run: cargo fmt -- --check

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.58.1
          target: wasm32-unknown-unknown
          override: true
      - name: Build
        run: cargo wasm --locked

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.58.1
          target: wasm32-unknown-unknown
          override: true
      - name: Run tests
        run: cargo unit-test
      - name: Run schema
        run: cargo schema
