name: Luna Vault

on:
  push:
    branches:
  pull_request:
    branches:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: contracts/luna-vault

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Install Rust
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        with:
          toolchain: 1.58.1
          target: wasm32-unknown-unknown
          components: clippy, rustfmt
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Run rustfmt
        run: cargo fmt -- --check

  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Install Rust
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        with:
          toolchain: 1.58.1
          target: wasm32-unknown-unknown
      - name: Build
        run: cargo wasm --locked

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Install Rust
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        with:
          toolchain: 1.58.1
          target: wasm32-unknown-unknown
      - name: Run tests
        run: cargo unit-test
      - name: Run schema
        run: cargo schema
